Switch from shade to openstacksdk
stackhpc/ansible-role-os-ironic-state pull request #4
Opened 2020-02-12 17:08 UTC by markgoddard

Shade is no longer required by upstream ansible modules.

2020-02-17 09:46 UTC, priteau requested changes

2020-02-17 09:46 UTC, priteau commented on README.md
> +The delegate host should have the `openstacksdk`Python  package installed.
There's a blank space character located in the wrong place here.

2020-02-17 09:46 UTC, priteau commented on library/os_ironic_state.py
> +IMPORT_ERRORS = []
Looks like `IMPORT_ERRORS` is only ever going to have zero or one element, is this pattern in case more imports are added in the future?

2020-02-20 11:32 UTC, markgoddard commented on library/os_ironic_state.py
> +IMPORT_ERRORS = []
Partly. It also generalises well to importing any module. I think I just copied it from another of our modules.

2020-02-20 11:38 UTC, priteau approved these changes

2020-02-20 15:27 UTC, merged